
sudo: false
language: cpp

os: linux
dist: trusty

#compiler:
#   - gcc
#   - clang

env:
  global:
    - DEPS_DIR=${TRAVIS_BUILD_DIR}/deps
    - BOOST_URL="http://sourceforge.net/projects/boost/files/boost/1.63.0/boost_1_63_0.tar.gz"
    - BOOST_VERSION="1_63_0"

cache:
  directories:
    - ${DEPS_DIR}/boost/

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test 
      - llvm-toolchain-trusty-5.0 

    packages:
      - cmake
      - ninja-build
      - g++-7

before_script:
    - |
      if [ ! -f "${DEPS_DIR}/boost/${BOOST_VERSION}_cached" ]; then
        # create dirs for source and install
        mkdir -p ${DEPS_DIR}/boost${BOOST_VERSION}
        mkdir -p ${DEPS_DIR}/boost
        rm -rf ${DEPS_DIR}/boost/*
        # download
        travis_retry wget --no-check-certificate --quiet -O - ${BOOST_URL} | tar --strip-components=1 -xz -C ${DEPS_DIR}/boost${BOOST_VERSION}
        pushd ${DEPS_DIR}/boost${BOOST_VERSION}
        # configure and install
        echo ./bootstrap.sh --prefix=${DEPS_DIR}/boost/ --with-libraries=date_time,filesystem,system,log,thread,program_options,regex,chrono,atomic
        ./bootstrap.sh --prefix=${DEPS_DIR}/boost/ --with-libraries=date_time,filesystem,system,log,thread,program_options,regex,chrono,atomic
        echo ./b2 toolset=gcc-7
        ./b2 toolset=gcc-7
        echo ./b2 -d0 install
        ./b2 -d0 install
        popd
        echo touch ${DEPS_DIR}/boost/${BOOST_VERSION}_cached
        touch ${DEPS_DIR}/boost/${BOOST_VERSION}_cached
        echo built boost ${BOOST_VERSION} successfully
      else
        echo 'Using cached Boost ${BOOST_VERSION} libraries.'
      fi
    - cmake --version
    - cd "${TRAVIS_BUILD_DIR}"
    - mkdir build && cd build
    - CC=gcc-7 CXX=g++-7 cmake .. -GNinja -DRAIBLOCKS_TEST=ON -DCMAKE_BUILD_TYPE=Release -DBOOST_ROOT=${DEPS_DIR}/boost

script:
    - cmake --build ${PWD} --

test_script:
    - ./core_test
